# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-13 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('lasttime', models.DateTimeField()),
            ],
            options={
                'db_table': 'browser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('list1', models.CharField(max_length=255)),
                ('list2', models.CharField(max_length=255)),
                ('list3', models.CharField(max_length=255)),
                ('list4', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ordertime', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=255)),
                ('phonenum', models.CharField(blank=True, max_length=255, null=True)),
                ('finishtime', models.DateTimeField(blank=True, null=True)),
                ('visible', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'db_table': 'orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.IntegerField()),
            ],
            options={
                'db_table': 'phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageurl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'picture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('restnum', models.IntegerField()),
                ('publishtime', models.DateTimeField()),
                ('finishtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'presale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('star', models.DecimalField(decimal_places=2, max_digits=5)),
                ('info', models.CharField(max_length=255)),
                ('publishdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchasetime', models.DateTimeField()),
                ('puchasenum', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prices', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restnum', models.IntegerField()),
            ],
            options={
                'db_table': 'storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('realname', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Walfare',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'walfare',
                'managed': False,
            },
        ),
    ]
