# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-14 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='img/%Y/%m/%d'),
        ),
    ]
