# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-16 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180914_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderid',
        ),
    ]
