# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-16 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20180916_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='orderid',
            field=models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.DO_NOTHING, to='mainsite.Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
