# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20180916_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', '待发货'), ('2', '预售等待'), ('3', '运送中'), ('4', '已收货'), ('5', '取消'), ('6', '退货中'), ('7', '退货完成')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='visible',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
